name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: cachix/install-nix-action@v31
      - name: Install gitleaks
        run: nix profile install nixpkgs#gitleaks
      - run: bun install --frozen-lockfile --no-verify
      - name: Run ci
        run: bun run ci
